### ISSUE TITLE
[3rd-Party-Apps] The nr1-pathpoint app does not run locally

### ISSUE THREAD

**Issue by jpvajda** [newrelic/nr1-pathpoint#14]
### Description

We were trying to update this app in the cantlog and it was failing, we then discovered it doesn't run locally so we'll need to spend some time investigating this. This app also seems to have it's own support system so not sure on that.

#### Catalog Merge Issue
There is an issue with the tests, they pass in a specific version number which is behind the current version of the app. I think just updating the relevant tests, as well as the sample JSON files to match `1.1.x` will suffice. The Schema checks to see if the first 2 numbers in the config `pathpointVersion` are the same as the current app version

 - [Failing Tests](https://github.com/newrelic/nr1-pathpoint/blob/main/nerdlets/pathpoint-nerdlet/__test__/schemas/view.test.js)
 - [Example PR](https://github.com/newrelic/nr1-catalog/runs/3974508680?check_suite_focus=true)
 - [JSON examples](https://github.com/newrelic/nr1-pathpoint/tree/main/examples)

### Build Issue
Seeing the following error when built locally:

```
4da92288-f951-41c5-a91c-9e45d4864ee9--pathpoint-nerdlet~latest.js:10878 Uncaught (in promise) Error: TypeError: Cannot read properties of undefined (reading 'id')
```

**Comment by jpvajda** [comment]
@rsamanez might be able to provide a review as well on this PR.https://github.com/newrelic/nr1-pathpoint/pull/16. I've also checked it out and had a comment.

**Comment by jpvajda** [comment]
I tested this PR, after running `nr1 nerdpack:uuid -gf` 😉  I'm not seeing any application load locally. @rudouglas 

<img width="1800" alt="Screen Shot 2021-11-10 at 3 13 39 PM" src="https://user-images.githubusercontent.com/1395158/141202488-e4bf22d9-3520-4eed-bcfa-675fcab502a8.png">

**Comment by rudouglas** [comment]
That's weird, I'm seeing results and i had to run `nr1 nerdpack:uuid -gf` 🍔 Are you seeing this error in the DevTools console:

```
Uncaught (in promise) Error: TypeError: Cannot assign to read only property 'status_on_off' of object '#<Object>'
```

I think that might be down to the Node version, try using Node 12 and reinstalling everything

**Comment by jpvajda** [comment]
@rudouglas it works now! Thanks for the suggestions, Stark Industries is back online.

<img width="1650" alt="Screen Shot 2021-11-11 at 3 09 33 PM" src="https://user-images.githubusercontent.com/1395158/141376090-c608aaf7-0441-4a4d-b380-29da62b7db2d.png">

**Comment by rudouglas** [comment]
I am Iron Man...duh duh duh duh dit do Iron Man 🦇
