### ISSUE TITLE
Error: No artifacts found

### ISSUE THREAD

**Issue by Husdady** [newrelic/nr1-pathpoint#47]
[NOTE]: # ( ^^ Failed to initialize development server ^^ )

## Description
I am trying to initialize the development server of a New Relic application. I cloned the current repository and updated the version. It is currently in version 1.6.3. I have two profiles: account-3490120 and wigiboards. After cloning the project. I install the dependencies with npm install. At the end of the installation, I generate an id with the following command nr1 nerdpack:uuid -gf --profile=wigiboards. And continue to start the server with the command: nr1 nerdpack:serve. Its here where the problem born. I need a lot of help, screenshot:

![image](https://user-images.githubusercontent.com/76859196/173456986-5e6caf52-b5ed-4824-afb8-52e75b1a4e5d.png)

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used: @datanerd/nr1/2.49.5 win32-x64 node-v14.15.1
* Browser name and version: Edge 102.0.1245.39
* Operating System and version: Window 8.1

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by JimHagan** [comment]
@Husdady can you still reproduce this with the latest CLI?

**Comment by Sandeep10parmar** [comment]
Closing this issue as there are no further updates. Please reopen as needed. 

cc: @JimHagan
