### ISSUE TITLE
`measure_time` is not being treated case insensitively (ignores lower case)

### ISSUE THREAD

**Issue by portoren** [newrelic/nr1-pathpoint#52]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

If in the JSON config file the measure_time is defined as "5 minutes ago", using lower case, this is interpreted as custom. The measure_time is only considered by default when it is set to uppercase with the value of “5 MINUTES AGO”. This causes the Time-Picker to have no effect on those touchpoints and can be confusing for the user.

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

1. Enter the Pathpoint menu to download the JSON config file.

![image](https://user-images.githubusercontent.com/2637031/202558300-16e2694e-016d-4997-8b6b-424d182b2647.png)

2. Select the “Json configuration” option from the menu and then click the download button.

![image](https://user-images.githubusercontent.com/2637031/202558343-f718250e-7180-4f91-9c09-53e08b1c43e2.png)

3. In the JSON config file, you can see the measute_time properties in lowercase and uppercase of two touchpoints of the same type.

![image](https://user-images.githubusercontent.com/2637031/202558507-60af9c5e-b12d-4ffd-be5c-9a69f6d91e6c.png)

4. When the Time-Picker is selected for example in “60 minutes ago” and we download the JSON-FILE again, we observe that this selection only has an effect on the touchpoints with the measure_time defined in uppercase, the touchpoints with the time defined in lowercase they are not affected because it is considered as custom:

![image](https://user-images.githubusercontent.com/2637031/202558616-e2c1a3fc-f4e2-4001-aed5-dd2cd27b1c18.png)

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

The interpreter of the measure_time attribute must recognize the default value of "5 Minutes Ago" with a case-insensitive filter.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used: @datanerd/nr1/2.83.5 win32-x64 node-v16.11.1
* Browser name and version: Firefox 107.0 (64 bit)
* Operating System and version: Windows 10
* Pathpoint version: 1.7.3

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by JimHagan** [comment]
Thanks for the submission @portoren .

I can see this is somewhat related to #51  but different enough to keep it separate.

My suggsetions

1. Make loading of the `measurement_time` to be case insensitive
2. As mentioned in #51 we should raise an exception when loading a JSON file with an `until` clause in the measurement name.  We don't want users setting an absolute end time for a time window.
3. Consider upper casing the measurement_time when a JSON is saved
4. Raise an error when the user tries save any of the of the following in a measurement_time
- an UNTIL clause
- missing a  `AGO` statement

**Comment by JimHagan** [comment]
@portoren Any more estimate on how long it may take to work on this?
